### ISSUE TITLE
Torrent files and images need to be stored locally or on an external fileserver

### ISSUE THREAD

**Issue by mickvandijke** [torrust/torrust-web-backend-old#1]
We need to store files, such as torrent and image files somewhere on a file server. We can store them locally on the host machine or an external file server such as Amazon S3/Backblaze.

Pros+/cons- storing files locally:
+ No dependency on external file server
+ Free
- Potentially slower in serving files than an external fileserver
- High bandwidth

Pros+/cons- storing files externally:
+ Fast file serving
+ Low bandwidth for host machine
- Not free
- dependency on external file server

**Comment by da2ce7** [comment]
I think that storing all the content locally is the preferable option.
